name = "atproto-auth-vue-starter"
main = "server/index.ts"
compatibility_date = "2025-07-05"
compatibility_flags = ["nodejs_compat"]
assets = { binding = "ASSETS" , not_found_handling = "single-page-application", run_worker_first = ["/auth/*", "/api/*"]}


